### ISSUE TITLE
Cannot Install `webpack-config-stream` from registry

### ISSUE THREAD

**Issue by eudisd** [mdreizin/webpack-config-stream#21]
`> npm install webpack-config-stream`                                                                                                                                          
```bash
npm WARN package.json crypto@0.0.3 crypto is also the name of a node core module.
npm WARN package.json fs@0.0.2 fs is also the name of a node core module.
npm WARN package.json fs@0.0.2 No description
npm WARN package.json fs@0.0.2 No repository field.
npm WARN package.json react-star-rating@1.3.2 No repository field.
npm ERR! Error: shasum check failed for /var/folders/wq/6qz3ygjx0ld0p51zxrtqlq8c0000gp/T/npm-85582-49hsdKen/registry.npmjs.org/webpack-config/-/webpack-config-1.1.0.tgz
npm ERR! Expected: ca2f3233d176c4bbe3b11f2f0687341b4c089ade
npm ERR! Actual:   100626b7aa29637ac99cffbf3f1354e6ca562a7e
npm ERR! From:     https://registry.npmjs.org/webpack-config/-/webpack-config-1.1.0.tgz
npm ERR!     at /Users/eudisduran/.nvm/v0.10.38/lib/node_modules/npm/node_modules/sha/index.js:38:8
npm ERR!     at ReadStream.<anonymous> (/Users/eudisduran/.nvm/v0.10.38/lib/node_modules/npm/node_modules/sha/index.js:85:7)
npm ERR!     at ReadStream.emit (events.js:117:20)
npm ERR!     at _stream_readable.js:944:16
npm ERR!     at process._tickCallback (node.js:448:13)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Darwin 15.0.0
npm ERR! command "/Users/eudisduran/.nvm/v0.10.38/bin/node" "/Users/eudisduran/.nvm/v0.10.38/bin/npm" "install" "webpack-config-stream"
npm ERR! cwd /Users/eudisduran/github/airtime/boba
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.28
npm ERR! not ok code 0
```

**Comment by mdreizin** [comment]
@eudisd I don't have any ideas why, I will try to publish to npm again.

**Comment by jowcy** [comment]
I'm seeing the same issue as well... (on OSX)

**Comment by adalgleish** [comment]
Same here.
```
    "webpack": "^1.12.2",
    "webpack-config": "^1.1.0"
```

**Comment by mdreizin** [comment]
@eudisd @jowcy @adalgleish I'm working on that.
